version: "3.7"
services:
    app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8080:8080"
        - "9229:9229"
      volumes:
        - ./src:/usr/src/app/src
        - ./package.json:/usr/src/app/package.json
      env_file:
        - .env
      depends_on:
        - db
      command: npm run start:dev

    db:
      container_name: db
      image: mongo:5.0
      ports:
        - "27017:27017"
      volumes:
        - db:/data/db
volumes:
  db:

